[project]
name = "letterboxed-solver"
version = "0.1.0"
requires-python = ">=3.9"

[project.optional-dependencies]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.9.4",
]
syncer = [
    "httpx>=0.28.1",
    "requests>=2.32.3",
    "trio>=0.28.0",
]